with Ada.Text_IO; use Ada.Text_IO;

with Terminal; use Terminal;

procedure Test_Colors is
begin
   Clear_Screen;
   Move_To (1, 1);
   Set_Color (Black);
   Put ("normal black ");
   Set_Color (Red);
   Put ("normal red ");
   Set_Color (Green);
   Put ("normal green ");
   Set_Color (Yellow);
   Put ("normal yellow ");
   Set_Color (Blue);
   Put ("normal blue ");
   Set_Color (Magenta);
   Put ("normal magenta ");
   Set_Color (Cyan);
   Put ("normal cyan ");
   Set_Color (White);
   Put ("normal white");
   Reset_Color;
   New_Line;
   Set_Color (Black, Bright);
   Put ("bright black ");
   Set_Color (Red, Bright);
   Put ("bright red ");
   Set_Color (Green, Bright);
   Put ("bright green ");
   Set_Color (Yellow, Bright);
   Put ("bright yellow ");
   Set_Color (Blue, Bright);
   Put ("bright blue ");
   Set_Color (Magenta, Bright);
   Put ("bright magenta ");
   Set_Color (Cyan, Bright);
   Put ("bright cyan ");
   Set_Color (White, Bright);
   Put ("bright white ");
   Reset_Color;
   New_Line;

   Set_Color (White);
   Put_Line ("Bright background colors:");
   Set_Background (Black, Bright);
   Put ("  BLACK   ");
   Set_Background (Red, Bright);
   Put ("   RED    ");
   Reset_Color;
   New_Line;
   Set_Color (White);
   Set_Background (Green, Bright);
   Put ("  GREEN   ");
   Set_Background (Yellow, Bright);
   Put ("  YELLOW  ");
   Reset_Color;
   New_Line;
   Set_Color (White);
   Set_Background (Blue, Bright);
   Put ("   BLUE   ");
   Set_Background (Magenta, Bright);
   Put (" MAGENTA  ");
   Reset_Color;
   New_Line;
   Set_Color (White);
   Set_Background (Cyan, Bright);
   Put ("   CYAN   ");
   Set_Background (White, Bright);
   Put ("  WHITE   ");
   Reset_Color;
   New_Line;
   Set_Color (White, Bright);
   Put_Line ("Normal background colors:");
   Set_Background (Black);
   Put ("  BLACK   ");
   Set_Background (Red);
   Put ("   RED    ");
   Reset_Color;
   New_Line;
   Set_Color (White, Bright);
   Set_Background (Green);
   Put ("  GREEN   ");
   Set_Background (Yellow);
   Put ("  YELLOW  ");
   Reset_Color;
   New_Line;
   Set_Color (White, Bright);
   Set_Background (Blue);
   Put ("   BLUE   ");
   Set_Background (Magenta);
   Put (" MAGENTA  ");
   Reset_Color;
   New_Line;
   Set_Color (White, Bright);
   Set_Background (Cyan);
   Put ("   CYAN   ");
   Set_Background (White);
   Put ("  WHITE   ");
   Reset_Color;
   New_Line;
   Set_Color (White);
   Set_Bright;
   Put ("bright ");
   Reset_Bright;
   Set_Dim;
   Put ("dim ");
   Reset_Dim;
   Set_Underline;
   Put ("underline ");
   Reset_Underline;
   Set_Blink;
   Put ("blink ");
   Reset_Blink;
   Set_Reverse;
   Put ("reverse ");
   Reset_Reverse;
   Set_Hidden;
   Put ("hidden ");
   Reset_Hidden;

   Reset_All;
   New_Line;
end Test_Colors;

